package org.puig.api.util.sat;

public enum RegimenesFiscales {
    GENERAL,
    INCORPORACION_FISCAL,
    CONTRIBUYENTES,
    INTERMEDIO,
    AGROPECUARIO,
    ENAJENACION_BIENES,
    COORDINADO,
    HIDROCARBUROS,
    MORAL_CON_FINES_NO_LUCRATIVOS,
    RESIDENTE_EXTRAJERO
}
